site_name: Talha Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - Kubernetes:
      - General:
          - Mapping API calls to Service backend: kubernetes/general/mappingAPICallsToServices.md
          - Setting Up K8s: kubernetes/general/settingUpKubernetes.md
          - Useful Extra Commands: kubernetes/general/usefulCommands.md
          - Debugging: kubernetes/general/debugging.md
      - Google:
          - Mounting application default credentials: kubernetes/google/mountingApplicationDefaultCredentials.md
      - Kind:
          - Kind Commands: kubernetes/kind/kindCommands.md
  - My Projects:
      - The Productive Muslim:
          - What I've Learned:
              - Cookies: myProjects/theProductiveMuslim/whatIveLearned/cookies.md
theme: material
