site_name: Talha Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - Data structures & Algorithms:
      - Binary Search: DataStructures_Algorithms/Binary_search.md
  - Kubernetes:
      - Basics:
          - Setting Up K8s: kubernetes/basics/settingUpKubernetes.md
          # - Switching Namespaces: kubernetes/basics/switchingNamespacesKubectl.md
          - Switching Workspace Cluster: kubernetes/basics/switchingClustersKubectl.md

      - General:
          - Finding ENV variables in pods and pulling them into containers: kubernetes/general/envVarsInPodsForContainers.md
          - Mapping API calls to Service backend: kubernetes/general/mappingAPICallsToServices.md

          - Useful Extra Commands: kubernetes/general/usefulCommands.md
          - Debugging: kubernetes/general/debugging.md
      - Cloudflare:
          - Connecting Ingress To Cloudflare Domain: kubernetes/cloudflare/connectingIngressToCloudflareDomain.md
          - Nginx Certification Configuration: kubernetes/cloudflare/nginxCertificates.md
      - Google:
          - Mounting application default credentials: kubernetes/google/mountingApplicationDefaultCredentials.md
      - Digital Ocean:
          - Authenticating and Pushing via Docker: kubernetes/digitalOcean/pushingToDORegistry.md
      - Kind:
          - Kind Commands: kubernetes/kind/kindCommands.md
          - Ingress Setup For Local Testing: kubernetes/kind/ingressOnKind.md
  - My Projects:
      - The Productive Muslim:
          - Overview: myProjects/theProductiveMuslim/overview.md
          - Why I Made The App (Learning): myProjects/theProductiveMuslim/whyIchoseToMakeIt.md
          - Skills Used In Project:
              - Go (Golang): myProjects/theProductiveMuslim/skillsUsedInProject/golang.md
              - Kubernetes: myProjects/theProductiveMuslim/skillsUsedInProject/kubernetes.md
              - Docker: myProjects/theProductiveMuslim/skillsUsedInProject/docker.md
              - Cookies: myProjects/theProductiveMuslim/skillsUsedInProject/cookies.md
              - JWT: myProjects/theProductiveMuslim/skillsUsedInProject/JWT.md
              - Password Encryption: myProjects/theProductiveMuslim/skillsUsedInProject/passwordEncryption.md
              - Login System: myProjects/theProductiveMuslim/skillsUsedInProject/loginSystem.md
              - Typescript: myProjects/theProductiveMuslim/skillsUsedInProject/typescript.md
              - NextJS: myProjects/theProductiveMuslim/skillsUsedInProject/nextJs.md
  - Go Notes:
      - Pointers: goNotes/pointers.md
      - HTTP:
          - Response Writers: goNotes/HTTP/responseWriters.md
          - Requests: goNotes/HTTP/requests.md
          - Serve Mux Path Types: goNotes/HTTP/serveMuxFixedPaths.md
          - Automatic Headers & Octet-Stream: goNotes/HTTP/octet-stream.md
  - Kafka Notes:
      - Notes: kafka/notes.md
  - Blockchain:
      - Basics: blockchain/blockchainBasics.md
  - C#:
      - Interfaces & Classes: csharp/Interfaces_and_classes.md
      - Dependency Injection: csharp/dependency_injection.md
  - Things I need to learn/do: needToLearn.md
theme: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
