site_name: Talha Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - Kubernetes:
      - Basics:
          - Setting Up K8s: kubernetes/basics/settingUpKubernetes.md
          - Switching Namespaces: kubernetes/basics/switchingNamespacesKubectl.md
          - Switching Workspace Cluster: kubernetes/basics/switchingClustersKubectl.md

      - General:
          - Finding ENV variables in pods and pulling them into containers: kubernetes/general/envVarsInPodsForContainers.md
          - Mapping API calls to Service backend: kubernetes/general/mappingAPICallsToServices.md

          - Useful Extra Commands: kubernetes/general/usefulCommands.md
          - Debugging: kubernetes/general/debugging.md
      - Google:
          - Mounting application default credentials: kubernetes/google/mountingApplicationDefaultCredentials.md
      - Kind:
          - Kind Commands: kubernetes/kind/kindCommands.md
          - Ingress Setup For Local Testing: kubernetes/kind/ingressOnKind.md
  - My Projects:
      - The Productive Muslim:
          - What I've Learned:
              - Cookies: myProjects/theProductiveMuslim/whatIveLearned/cookies.md
theme: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
